config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end
  
  resources :users do
    member do
      get :delete
    end
  end

  resources :projects do

    resources :bugs do
      get :delete
    end
    put '/bugs/:id/assign', to: 'bugs#assign', as: 'assign_bug'

    member do
      get :delete
    end
  end
  
  # resources :bugs do
  #   member do
  #     get :delete
  #   end
  # end
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  enum status: [ :solved, :unsolved, :handling, :ignored]

  belongs_to :project
  has_and_belongs_to_many :users
end

app/models/project.rb
class Project < ApplicationRecord
  attr_accessor :u_id
  
  has_many :bugs
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_and_belongs_to_many :projects

  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :accept_invitation, keys: [:email]
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :project_id
  def index
    @bugs=Bug.where(:project_id => params[:project_id])
  end

  def show
    @bug=Bug.find(params[:id])
    
  end

  def new
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.new
    @project_id=params[:project_id]
  end

  def create
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.new
    if @bug.save
      redirect_to(projects_path)
    else
      render('new')
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @bug = @project.bugs.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])
    if @bug.update(bug_params)
      redirect_to(project_bugs_path(@project))
    else
      render('edit')
    end
  end

  def delete
    @bug=Bug.find(params[:id])
  end

  def destroy
    @bug=Bug.find(params[:id])
    @bug.destroy
    redirect_to(projects_path)
  end

  def assign
    @bug = Bug.find(params[:id])
    @bug.user = current_user
    if @bug.save
      redirect_to(project_bugs_path(@project_id))
    else
      render('edit')
    end
  end

  private
  def bug_params
    params.require(:bug).permit(:bug_name, :bug_description, :project_id, :user, :status)
  end

  def project_id
    @project_id = params[:project_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def dashboard
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!

  def index
      @project = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
  
  def new
    @project = Project.new
    @users = User.all
  end

  def create
    @project = Project.new(project_params)
    # binding.pry
    users = User.where(id: params[:project][:u_id])
    @project.users << users
    if @project.save
      flash[:notice] = "Project created"
      redirect_to(projects_path)
    else
      render('new')
    end
  end

  def edit
    @project=Project.find(params[:id])
  end

  def update
    @project=Project.find(params[:id])
    users = User.where(id: params[:project][:u_id])
    old_users = @project.users
    old_users << users
    @project.users = old_users.uniq

    if @project.update(project_params)
      redirect_to(project_path(@project))
    else
      render('edit')
    end
  end

  def delete
    @project=Project.find(params[:id])
  end

  def destroy
    @project= Project.find(params[:id])
    @project.destroy
    redirect_to(projects_path)
  end

  private
  
  def project_params
    params.require(:project).permit(:project_name, :project_description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bug_helper.rb
module BugHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def dashboard_menu_options
    links = ""

    if current_user.admin?
      links += link_to "Invite User", new_user_invitation_path
      links += link_to "Users", users_path
    end
    links += link_to "Projects", projects_path 
    links += link_to "Sign Out", destroy_user_session_path, :method => :delete
    links
  end
end

app/helpers/project_helper.rb
module ProjectHelper

  def show_emails
    link = ""
    @project.users.map do |i|
      link +=i.email + "<br>"
    end
    link.html_safe
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<table summary="Bug form fields">
 <tr>
    <th>Name</th>
    <td><%= f.text_field(:bug_name) %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_field(:bug_description) %></td>
  </tr>
  <tr>
    <th>Status</th>
    <td><%= f.select :status, Bug.statuses.keys %></td>
  </tr>    
</table>

app/views/bugs/edit.html.erb
<h1>Edit</h1>

<%=link_to "Get back",projects_path%>
<%= form_for([@project,@bug]) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f})%>    
   
    <div class="form-buttons">
      <%= f.submit("Create Bug") %>
    </div>

  <% end %>

app/views/bugs/index.html.erb
<%= link_to "<<Project List", projects_path %>
<h1>List of bugs</h1>


  <table class="listing" summary="Bug list">
    <tr class="header">
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
    <% @bugs.each do |bug| %>
    <tr>
      <td><%= bug.id%></td>
      <td><%= bug.bug_name %> </td>
      <td><%= bug.bug_description %> </td>
      <td><%= bug.status %></td>      
      <td><%= link_to("update", edit_project_bug_path(bug.project_id,bug))%></td>
      <!--can use "pages/#{bug.id}" or "subject_path(bug) or {:controller => bugs, :action => show, :id => bug.id}"-->
      <td><%= link_to("assign", project_assign_bug_path(bug.project_id,bug), :method => :put)%></td>
     
    </tr>
    <% end %>
  </table>

app/views/bugs/new.html.erb
<h1>Bug add</h1>
<%=link_to "Get back",projects_path%>
<%= form_for([@project, @bug]) do |f| %>

  <%= render(:partial => 'form', :locals => {:f => f})%>    
   
    <div class="form-buttons">
      <%= f.submit("Create Bug") %>
    </div>

  <% end %>

app/views/bugs/show.html.erb
<%=link_to "Back to project",projects_path%>
<h1>Bug Detail</h1>

<table>
  <tr>
    <td>Bug ID </td>
    <td><%=@bug.id%></td>
  <tr>
    <td>Name</td>
    <td><%=@bug.bug_name%></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%=@bug.bug_description%></td>
  </tr>
  </tr>
    <td>Project ID </td>
    <td><%=@project_id%></td>
  </tr>

</table>

app/views/home/dashboard.html.erb
<%# signout link
# User link
# project
# bug %>
<h1> Dash Board</h1>

<%= dashboard_menu_options.html_safe %>

app/views/home/index.html.erb
<h1>Welcome</h1>
<h2>Please Log in </h2>
<%= link_to "Sign In", new_user_session_path%> <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingTool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

   <table summary="Project form fields">
     <tr>
       <th>Project</th>
       <td><%= f.text_field(:project_name) %></td>
     </tr>
     <tr>
       <th>Project Description</th>
       <td><%= f.text_area(:project_description) %></td>
     </tr>
     <tr>
       <th>User</th>
        <td>
          <%=f.collection_select(:u_id, User.all, :id, :email,{}, {:prompt => true, :multiple=>true })%>
        </td>
      </tr>
     <tr>
   </table>

   <div class="form-buttons">
     <%= f.submit("Create Project") %>
   </div>
<%end%>  

app/views/projects/delete.html.erb
<%= link_to("<< Back to List", projects_path, :class => 'back-link') %>


  <h2>Delete Project</h2>

  <%= form_for(@project, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this project?</p>

    <p class="reference-name"><%= f.object.project_name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Project") %>
    </div>

  <% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%=link_to "Get back", projects_path%>

<%= render partial: 'form' %>

app/views/projects/index.html.erb
<div class="users index">
  <h2>Project</h2>
  <%= link_to("Add Project", new_project_path) %>
  <table class="listing" summary="User list">
    <tr class="header">
      <th>#</th>
      <th>Project</th>
      <th>User</th>
      <th>Description</th>
      <th>Actions</th>
      <th>Bugs<th>
    </tr>

    <% @project.each do |project| %>
    <% if project.user_ids.include?(current_user.id) || current_user.admin %>
    <tr>
      <td><%=project.id%> </td>
      <td><%=project.project_name%></td>
      <td><%=project.user_ids %></td>
      <td><%=project.project_description %> </td>
      <td><%= link_to("Show", project_path(project)) %>
        <%= link_to("Edit", edit_project_path(project)) %>
        <%= link_to("Delete", delete_project_path(project)) %>
      </td>
      <td>
        <%= link_to("Add bug", new_project_bug_path(project), :class => 'action new') %>
        <%= link_to("Show bugs", project_bugs_path(project), :class => 'action new') %>
      </td>
    </tr>
    <%end%>
    <%end%>
  </table>
  <%= link_to "Back", :back%>
</div>

app/views/projects/new.html.erb
<h1>Project add</h1>

<%=link_to "Get back", projects_path%>

<%= form_for(@project) do |f| %>

   <table summary="Project form fields">
     <tr>
       <th>Project</th>
       <td><%= f.text_field(:project_name) %></td>
     </tr>
     <tr>
       <th>Project Description</th>
       <td><%= f.text_area(:project_description) %></td>
     </tr>
     <tr>
       <th>User</th>
        <td>
          <%=f.collection_select(:u_id, User.all, :id, :email,{}, {:prompt => true, :multiple=>true })%>
        </td>
      </tr>
     <tr>
   </table>

   <div class="form-buttons">
     <%= f.submit("Create Project") %>
   </div>
<%end%>  

app/views/projects/show.html.erb
<%=link_to "Get back",projects_path%>
<h1>Project Detail</h1>

<table>
  <tr>
    <td>Project ID </td>
    <td><%=@project.id%></td>
  <tr>
    <td>Name</td>
    <td><%=@project.project_name%></td>
  </tr>
    <td>Description</td>
    <td><%=@project.project_description%></td>
  </tr>
  </tr>
    <td>Assigned User No</td>
    <td><%=@project.user_ids%></td>
  </tr>
  </tr>
    <td>Assigned User Emails</td>
    <td>
    <%=show_emails%>
    </td>
  </tr>
</table>

app/views/users/index.html.erb
<div class="users index">
  <h2>Subjects</h2>

  <table class="listing" summary="User list">
    <tr class="header">
      <th>#</th>
      <th>User</th>
      <th>Accepted</th>
      <th>Action</th>
    </tr>
    <% @users.each do |user| %>
    <%if current_user.email != user.email%>
    <tr>
      <td><%=user.id-1%> </td>
      <td><%=user.email %> </td>
      <td><%=user.invitation_accepted_at ? 'Yes' : 'No' %> </td>
      <td><%= link_to("Show", user_path(user)) %>
        <%= link_to("Edit", edit_user_path(user)) %>
        <%= link_to("Delete", delete_user_path(user)) %></td>
    </tr>
    <%end%>
    <% end %>
  </table>
  <%= link_to "Back", :back%>
</div>